### ISSUE TITLE
I've deleted all versions of my pod and now I can't push anything there

### ISSUE THREAD

**Issue by viacheslavleonov** [CocoaPods/cocoapods-trunk#57] opened 2016-04-01 13:45 UTC
Hello. 
I've been deploying new pod to the trunk and pushed several beta versions last week. Today I've deleted all of them using "pod trunk delete" and my pod vanished from the Specs rep. But it's show in the list of pods on cocoapods.org but I can't click on it. 
The main problem is that I can not push any new version right now. I receive error "[!] {"name"=>["is already taken"]}"
Looks like pod was deleted from Specs rep after last version was deleted, but it was not deleted from trunk. And now I can't do anything with this pod.

Could you completely delete it so I will start from scratch? This will not affect any users cause we didn't go public yet. 
Pod name is 'ampiri-ios-sdk'
And this bug should be fixed somehow, do not allow to delete last version or delete pod completely if last version was deleted.

**Comment by segiddins** [comment] 2016-04-01 16:28
This is a duplicate of https://github.com/CocoaPods/trunk.cocoapods.org/issues/172 -- we hope to get around to fixing it soon!

**Closed by segiddins** 2016-04-01 16:28 UTC
